# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "Posts"
  url = "/posts/"
  # title will be shown when you hover on this menu link.
  # 将鼠标悬停在此菜单链接上时将显示标题。
  title = ""
  weight = 1
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 2
[[main]]
  weight = 3
  identifier = "contact"
  pre = ""
  post = ""
  name = "Contact"
  url = "/contact/"
  title = ""
[[main]]
  weight = 4
  identifier = "talks"
  pre = ""
  post = ""
  name = "Talks"
  url = "/talks/"
  title = ""
[[main]]
  weight = 5
  identifier = "speaker-resume"
  pre = ""
  post = ""
  name = "Speaker Resume"
  url = "/speaker-resume/"
  title = ""
[[main]]
  weight = 6
  identifier = "teaching"
  pre = ""
  post = ""
  name = "Teaching"
  url = "/teaching/"
  title = ""
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""
  weight = 8
