# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: blog.touret.info
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Mon blog personnel. J'y expose mes derniers travaux , ma veille technologique sur le développement spring, le cloud et les logiciels libres. J'abord également les derniers talks que j'ai pu réaliser.
twitter_username: touret_alex
github_username: alexandre-touret
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: fr

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alexandre Touret"
  avatar : "/assets/images/bouletmaton1.jpg "
  bio    : "Architecte logiciel et développeur (senior pour les deux)"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/touret_alex"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexandre-touret"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/atouret/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/touret_alex"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexandre-touret"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/atouret/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

locale: fr

domain: blog.touret.info      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://blog.touret.info  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /    # place folder name if the site is served in a subfolder
repository: alexandre-touret/alexandre-touret.github.io

feed:
  tags: true
date_format: "%d/%m/%Y"
google-site-verification: "7UnqNmvO-mjfMkRqKaaWRPTBxSylEVJXvAn8iTfc7SI"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: " UA-31817514-1"
    anonymize_ip: false # default
