# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: blog.touret.info
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Mon blog personnel. J'y expose mes derniers travaux et ma veille technologique. Au menu en vrac: Java, Kotlin, Maven, Docker, Cloud, Kubernetes, logiciels libres, Debian, Ubuntu, Gnu/Linux, des talks online et présentiels.
twitter_username: touret_alex
github_username: alexandre-touret
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: fr

include:
  - _pages
  - CNAME

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - publish_drafts.py
  - LICENSE
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Alexandre Touret"
  avatar : "/assets/images/bouletmaton1.jpg"
  bio    : "Architecte logiciel, développeur, bidouilleur (dans le désordre)"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/touret_alex"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexandre-touret"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/atouret/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/touret_alex"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexandre-touret"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/atouret/"
    - label: "Licence du contenu de ce site"
      icon: "fab fa-fw fa-creative-commons-by"
      url: "https://creativecommons.org/licenses/by/4.0/"
    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

locale: fr

domain: blog.touret.info      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://blog.touret.info  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /    # place folder name if the site is served in a subfolder
repository: alexandre-touret/alexandre-touret.github.io
canonical_url: https://blog.touret.info
feed:
  tags: true
date_format: "%d/%m/%Y"
google-site-verification: "7UnqNmvO-mjfMkRqKaaWRPTBxSylEVJXvAn8iTfc7SI"
bing_site_verification: "F9655A4C8648E42154ECB4B4D6CF60A2"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: " UA-31817514-1"
    anonymize_ip: false # default
twitter:
  username: "touret_alex"
og_image: /assets/images/bouletmaton1.jpg

social:
  links:
    - "https://twitter.com/touret_alex"
    - "https://www.linkedin.com/in/atouret"

sass:
  style: compressed

comments:
  provider: "utterances"
  utterances:
    repository: "alexandre-touret/alexandre-touret.github.io"
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.

# Code snippets customization
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Adding copy-to-clipboard functionality
after_footer_scripts:
  - https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  - assets/js/clipboardrouge.js