@startuml batch_evenement
!include ../../../plantuml/include/C4_Container.puml
!include ../../../plantuml/include/C4_Context.puml

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title Batch sur presence fichier
Person(user, "User")
' Container_Ext(gslb,"GSLB","GSLB","Load balancing")

System_Boundary(dc1, "System") {
    Container(gateway,"File Gateway","AWS File Gateway,... ","Accepts files from trusted customers")
    Container(s3,"File Storage","AWS S3,GCP Filestore... ","Stores files")

    Boundary(instance1, "Instance #1") {

    Container(batch, "Batch Java Application", "Java, ...", "Polls the S3 buckets and handle new files")
    }

    ContainerDb(db1, "Database", "PostgreSQL", "Stores data", "pgsql_server")
}


Rel(gateway,s3,"Stores","HTTPS")
Rel(user, gateway, "Uses", "HTTPS")
Rel(batch, s3, "Polls & Fetch", "HTTPS")
Rel(batch, db1, "queries", "JDBC")

@enduml
