name: Publish Drafts
on:
  milestone:
    types: [closed]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: 📂 setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7' # install the python version needed
    - name: 💎 install python packages
      run: |
        python -m pip install --upgrade pip
          
    - name: 🔨 execute py script 
      run: python publish_drafts.py
          
    - name: 🔨 commit files
      run: |
        if git ls-files -o  --exclude-standard; then
          git config --local user.email "${{ secrets.GITHUBUSEREMAIL}}"
          git config --local user.name "${{ secrets.GITHUBUSERNAME}}"
          git add -A
          git commit -m "publish drafts" -a
          git push origin main
        else
          echo "No file to publish"
        fi
          
